In [51]:
import pandas as pd
import numpy as np

In [52]:
import kagglehub
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.

In [53]:
import os
print(os.listdir(path))

['IMDB Dataset.csv']

In [54]:
df = pd.read_csv(os.path.join(path,'IMDB Dataset.csv'))

In [55]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [56]:
df['review'] = df['review'].str.lower()

In [57]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [58]:
import re
def remove_html_tags(text):
  pattern = re.compile('<.+?>')
  return pattern.sub(r'',text)

In [59]:
df['review'] = df['review'].apply(remove_html_tags)

In [60]:
df.head(3)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive

In [61]:
def remove_url(text):
  pattern = re.compile(r"((?:https?://|www\.)[^\s]+)")
  return pattern.sub(r'',text)

In [62]:
df['review'] = df['review'].apply(remove_url)

In [63]:
df.head(1)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive

In [64]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [65]:
exclude=string.punctuation
def remove_punc(text):
  for char in exclude:
    text = text.replace(char,'')
  return text

In [66]:
text='string. with . pnaction?'

In [67]:
start=time.time()
print(remove_punc(text))
end1 = time.time() - start
print(end1*50000)

string with  pnaction
8.726119995117188

In [68]:
def remove_punc1(text):
  return text.translate(str.maketrans('','',exclude))

In [69]:
start=time.time()
print(remove_punc1(text))
end2 = time.time() - start
print(end2*50000)

string with  pnaction
32.651424407958984

In [70]:
end1/end2

0.2672508214676889

In [71]:
from textblob import TextBlob

In [72]:
incorrect= 'ceertain conditons durign'

In [73]:
textblob = TextBlob(incorrect)
textblob.correct().string

'certain conditions during'

In [74]:
import nltk

In [75]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [76]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [77]:
def remove_stopwords(text):
  new_text=[]

  for word in text.split():
    if word in stopwords.words('english'):
      new_text.append('')
    else:
      new_text.append(word)
  x= new_text[:]
  new_text.clear()
  return " ".join(x)

In [80]:
new_df = df.sample(100)

In [81]:
new_df['review']=new_df['review'].apply(remove_stopwords)

In [82]:
!pip install emoji

Requirement already satisfied: emoji in /usr/local/lib/python3.12/dist-packages (2.15.0)

In [83]:
import emoji
#remove emoji
text = "Hello World! 🌍😀"
clean_text = emoji.replace_emoji(text, replace='')
print(clean_text)

Hello World!

In [84]:
#replace emoji
print(emoji.demojize(text))

Hello World! :globe_showing_Europe-Africa::grinning_face:

# **1.Using the Split Function**

In [85]:
sent1=' I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [86]:
sent2=' I am going to delhi. I will stay for 3 days .Let\'s hope the trip to be great '
sent2.split('.')

[' I am going to delhi',
 ' I will stay for 3 days ',
 "Let's hope the trip to be great "]

In [87]:
sent3='I am going to Delhi!'
sent3.split()# delhi! and delhi are now to different words

['I', 'am', 'going', 'to', 'Delhi!']

In [88]:
sent4='Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

# **2. Regular Expression**

In [89]:
import re
sent3='I am going to delhi!'
tokens=re.findall(r"[\w']+",sent3)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [92]:
text = df['review'][0]
sentences=re.compile('[.!?]').split(text)
sentences

["one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked",
 ' they are right, as this is exactly what happened with me',
 'the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go',
 ' trust me, this is not a show for the faint hearted or timid',
 ' this show pulls no punches with regards to drugs, sex or violence',
 ' its is hardcore, in the classic use of the word',
 'it is called oz as that is the nickname given to the oswald maximum security state penitentary',
 ' it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda',
 ' em city is home to many',
 '',
 'aryans, muslims, gangstas, latinos, christians, italians, irish and more',
 '',
 '',
 '',
 'so scuffles, death stares, dodgy dealings and shady agreements are never far away',
 "i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare",
 ' forget pretty pictures painted for mainstream audiences, forget charm, forget romance',
 '',
 '',
 "oz doesn't mess around",
 " the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence",
 " not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing",
 '',
 '',
 '',
 'thats if you can get in touch with your darker side',
 '']

In [93]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [97]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [102]:
sent1=' I am going to delhi!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'delhi', '!']

In [103]:
sent_tokenize(text)

["one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked.",
 'they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go.',
 'trust me, this is not a show for the faint hearted or timid.',
 'this show pulls no punches with regards to drugs, sex or violence.',
 'its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary.',
 'it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda.',
 "em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare.",
 "forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around.",
 "the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence.",
 "not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."]

In [113]:
sent5='I have Ph.D in A.I'
word_tokenize(sent5)

['I', 'have', 'Ph.D', 'in', 'A.I']

In [112]:
sent6="We're here to help! mail us at nks@gmail.com"
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [114]:
import spacy

In [115]:
nlp=spacy.load('en_core_web_sm')

In [117]:
doc1=nlp(sent5)
doc2=nlp(sent6)

In [120]:
for tokens in doc2:
  print(tokens)

We
're
here
to
help
!
mail
us
at
nks@gmail.com

In [121]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [122]:
def stem_words(text):
  return " ".join(ps.stem(word) for word in text.split())

In [123]:
sample="walk walking walked walks"

In [124]:
stem_words(sample)

'walk walk walk walk'

In [124]:
from nltk.tokenize.sonority_sequencing import punctuation
from nltk(.stem import WordNetLemmatizer
wl=WordNetLemmatizer
sentence='He was running and eating at same time . he has bad habit of swimming after playing long hours in the Sun'
punctions="?:!.,;"
sentence_words=nltk.word_tokenize(sentence)
for word in sentence_words:
          if word in punctuations:

In [130]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
wl = WordNetLemmatizer()

sentence = 'He was running and eating at same time. he has bad habit of swimming after playing long hours in the Sun'

punctuations = "?:!.,;"

sentence_words = nltk.word_tokenize(sentence)

for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

print('{0:20}{1:20}'.format('Word', 'Lemma'))

for word in sentence_words:
    print('{0:20}{1:20}'.format(word, wl.lemmatize(word,pos='v')))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
he                  he
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!